### ISSUE TITLE
make should use a "configurable" -j

### ISSUE THREAD

**Issue by jaynel** [docker-file/erlang#2]
My upgrade added '-j4' as a hack to making openssl and erlang more quickly. When running in the cloud there may or may not be cores available. The code should either have a configurable parameter or somehow detect and supply a good value.

I assume 4 is not too aggressive, and if there aren't enough cores it will not slow down too dramatically compared to forcing everyone to run as if they had one core.

**Comment by fogfish** [comment]
Hmm, just build everything successful on 2x core machine... I do not think that this is a critical and -j4 sounds reasonable to me. Anyway, you'll build the docker container and publish it to docker hub, where clients can pull it out...
